# Generated by Django 3.2.4 on 2021-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0006_auto_20210710_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
    ]
